
MUSIC_DATA_FOLDER = './data/music_data'
DISEASE_DATA_FOLDER = './data/disease_data'
CLOUD_ID = 'My_deployment:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyQwMTVlYjA2MmYzOWU0NGRjOTdhMWNhNGEzMTkxZmYxYyQxYmJiNDczZTkxYmE0ZWQ2ODYxNTkyNThhNTA0MDVmMw=='
API_KEY = 'NUFqWG5wTUJLdE94Q0ExMGJ2b0w6eW5FeDJxSG9Rc210MXdZMXlqNVRPQQ=='
INDEX_NAME = 'new_rock_vn'